//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int E_Id { get; set; }
        public string E_name { get; set; }
        public Nullable<int> E_salary { get; set; }
        public Nullable<int> E_age { get; set; }
        public string E_dob { get; set; }
        public string E_hometown { get; set; }
    }
}
